### ISSUE TITLE
AttributeError: 'list' object has no attribute 'push'

### ISSUE THREAD

**Issue by arabelle** [stdlib/lib-python#3]
I am trying to import the lib package in my python application and it seems to run into a problem where the package has a bug (as shown below)
```
ERROR:tornado.application:Uncaught exception POST /image?
...
Traceback (most recent call last):
...
  File "/usr/local/lib/python2.7/dist-packages/lib/__init__.py", line 136, in __call__
    body = self.__py2body__(args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/lib/__init__.py", line 204, in __py2body__
    a.push(value)
AttributeError: 'list' object has no attribute 'push'
```
All I am doing is `from lib import lib`. 

Is this a known problem? I am running this in a docker container where I run:
`pip install lib` on it.

**Comment by malkevych** [comment]
try import is as 
`from lib import lib as lib_inst`
